HTTPConnectionPool(host='0.0.0.0', port=17678): Max retries exceeded with url: /api/state (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x042310E8>: Failed to establish a new connection: [WinError 10049] Требуемый адрес для своего контекста неверен'))
