{
  "uid" : "17bb19224b7a1dd5",
  "name" : "test_zero_division_error[1-0-division]",
  "fullName" : "tests.test_functionality#test_zero_division_error",
  "historyId" : "2540d824f118bf9cde4633e76f8cd6d8",
  "time" : {
    "start" : 1649597959843,
    "stop" : 1649597959850,
    "duration" : 7
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL Статус-код не соответствует ТЗ\n\nAssertionError: assert {'statusCode': 8, 'statusMessage': 'Ошибка вычисления'} == {'statusCode': 1, 'statusMessage': 'Ошибка вычисления'}\n  Common items:\n  {'statusMessage': 'Ошибка вычисления'}\n  Differing items:\n  {'statusCode': 8} != {'statusCode': 1}\n  Full diff:\n  - {'statusCode': 1, 'statusMessage': 'Ошибка вычисления'}\n  ?                ^\n  + {'statusCode': 8, 'statusMessage': 'Ошибка вычисления'}\n  ?                ^",
  "statusTrace" : "x = 1, y = 0, task = 'division'\n\n    @pytest.mark.xfail(reason=\"Статус-код не соответствует ТЗ\", strict=True)\n    @pytest.mark.parametrize(\"x, y, task\", [(1, 0, \"division\"), (1, 0, \"remainder\")])\n    def test_zero_division_error(x, y, task):\n        respond = requests.post(f\"http://{HOST}:{PORT}/api/{task}\", json={\"x\": x, \"y\": y})\n>       assert respond.json() == {'statusCode': 1, 'statusMessage': 'Ошибка вычисления'}\nE       AssertionError: assert {'statusCode': 8, 'statusMessage': 'Ошибка вычисления'} == {'statusCode': 1, 'statusMessage': 'Ошибка вычисления'}\nE         Common items:\nE         {'statusMessage': 'Ошибка вычисления'}\nE         Differing items:\nE         {'statusCode': 8} != {'statusCode': 1}\nE         Full diff:\nE         - {'statusCode': 1, 'statusMessage': 'Ошибка вычисления'}\nE         ?                ^\nE         + {'statusCode': 8, 'statusMessage': 'Ошибка вычисления'}\nE         ?                ^\n\ntest_functionality.py:60: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "newBroken" : false,
  "newPassed" : false,
  "retriesCount" : 0,
  "retriesStatusChange" : false,
  "beforeStages" : [ {
    "name" : "setup_app",
    "time" : {
      "start" : 1649597897212,
      "stop" : 1649597902123,
      "duration" : 4911
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ {
    "name" : "setup_app::0",
    "time" : {
      "start" : 1649597959878,
      "stop" : 1649597961967,
      "duration" : 2089
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(reason='Статус-код не соответствует ТЗ', strict=True)"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_functionality"
  }, {
    "name" : "host",
    "value" : "LAPTOP-60Q9K2PF"
  }, {
    "name" : "thread",
    "value" : "4580-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_functionality"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "task",
    "value" : "'division'"
  }, {
    "name" : "x",
    "value" : "1"
  }, {
    "name" : "y",
    "value" : "0"
  } ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "@pytest.mark.xfail(reason='Статус-код не соответствует ТЗ', strict=True)" ]
  },
  "source" : "17bb19224b7a1dd5.json",
  "parameterValues" : [ "'division'", "1", "0" ]
}